import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { Montserrat } from "next/font/google";


const montserrat = Montserrat({ 
  subsets: ['latin'],
  variable: '--montserrat-font',
});

export const metadata: Metadata = {
  title: "LP Cosmetics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
